apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: l2vlk7ju0-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-19b6c351a2.qq9q.p3.openshiftapps.com/rhtap/rhtap-qe-dotnet-basic:b43f015fef523a85937b8265bff66d5d95a07a89@sha256:b082bb964861ac5fcabb20758cb6ac6c9d2044c36233fcc2a3a0e3204e18d854
          name: container-image
